apiVersion: v1
kind: Pod
metadata:
  name: fileorganizer-2000-pod
  labels:
    app: fileorganizer-2000
spec:
  automountServiceAccountToken: false
  containers:
    - name: fileorganizer-2000-container
      image: fileorganizer-2000:20241028
      ports:
        - containerPort: 3000
      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: fo2k-secret
              key: OPENAI_API_KEY
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          ephemeral-storage: "2Gi"
