apiVersion: v1
kind: Pod
metadata:
  name: fileorganizer-2000-pod
  labels:
    app: fileorganizer-2000
spec:
  automountServiceAccountToken: false
  containers:
    - name: fileorganizer-2000-container
      image: fo2k-backend:latest
      ports:
        - containerPort: 3000
          hostPort: 3001
      env:
        - name: OPENAI_API_KEY
          valueFrom:
             secretKeyRef:
               name: fo2k-secret
               key: OPENAI_API_KEY
        - name: MODEL_FOLDERS
          value: "llama3.2"
        - name: MODEL_RELATIONSHIPS
          value: "llama3.2"
        - name: MODEL_TAGGING
          value: "llama3.2"
        - name: MODEL_NAME
          value: "llama3.2"
        - name: MODEL_TEXT
          value: "llama3.2"
        - name: MODEL_VISION
          value: "llava-llama3"
        - name: OLLAMA_API_URL
          value: "http://host.docker.internal:11434/"
        - name: PORT
          value: "3000"
        - name: USE_OLLAMA
          value: "true"
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          ephemeral-storage: "2Gi"
